# Copyright (c) 2022 Yegor Bugayenko
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: make
on:
  push:
    branches:
      - master
    paths-ignore: [ 'README.md', 'LICENSE.txt' ]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  start-instance:
    runs-on: ubuntu-24.04
    outputs:
      label: ${{ steps.start.outputs.label }}
      ec2-instance-id: ${{ steps.start.outputs.ec2-instance-id }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - id: start
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PAT }}
          ec2-image-id: ami-0a4d66b921e31d780
          ec2-instance-type: t2.small
          subnet-id: subnet-0f80650e7db6e041e
          security-group-id: sg-0ffb312e3a7d40ed3
  build:
    needs: start-instance
    runs-on: ${{ needs.start-instance.outputs.label }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo make install
      - run: |
          sudo mkdir -p /opt/hostedtoolcache \
            && sudo chown $(whoami) /opt/hostedtoolcache
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: false
      - run: gem install xcop
      - run: |
          sudo mkdir -p /usr/local/opt
          sudo wget --no-verbose -O /usr/local/opt/Saxon.jar https://repo.maven.apache.org/maven2/net/sf/saxon/Saxon-HE/9.8.0-5/Saxon-HE-9.8.0-5.jar
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: rm -rf ~/.graalvm
      - uses: graalvm/setup-graalvm@v1.2.3
        with:
          distribution: 'graalvm'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GH_PAT }}
      - run: |
          if [ ! -e /usr/bin/perf ]; then
            sudo apt-get install -y linux-tools-generic
            sudo ln -s "$(ls /usr/lib/linux-tools/*/perf | head -1)" /usr/bin/perf
          fi
      - run: make env
      - run: make clean
      - run: mkdir www
      - run: make WANTED=256 INPUT=7 index.html
      - run: mv index.html www/seven.html
      - run: rm -rf reports
      - run: make WANTED=256 INPUT=16 index.html
      - run: mv index.html www/sixteen.html
      - run: rm -rf reports
      - run: make WANTED=256 index.html
      - run: cp index.html www
      - run: cp index.xml www
      - run: cp -r reports www
      - run: cp -r asm www
      - uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          branch: gh-pages
          folder: www
          clean: false
  terminate-instance:
    needs:
      - start-instance
      - build
    runs-on: ubuntu-24.04
    if: ${{ always() }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PAT }}
          label: ${{ needs.start-instance.outputs.label }}
          ec2-instance-id: ${{ needs.start-instance.outputs.ec2-instance-id }}
