# Copyright (c) 2022 Yegor Bugayenko
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: quick
'on':
  pull_request:
jobs:
  quick:
    runs-on: ubuntu-20.04
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - run: gem install xcop
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/setup-go@v5
      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: egor-tensin/setup-clang@v1
        with:
          version: 13
      - run: sudo apt-get install -y clang-tidy-13 clang-format-13
      - run: |
          for f in clang++ clang-tidy clang-format; do
            if [ -e /usr/bin/${f} ]; then sudo unlink /usr/bin/${f}; fi
            sudo ln -s /usr/bin/${f}-13 /usr/bin/${f}
          done
      - run: |
          sudo add-apt-repository ppa:eiffelstudio-team/ppa
          sudo apt-get update
          sudo apt-get install eiffelstudio
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt-get install -y gnat
      - run: pip install cpplint
      - run: sudo apt-get install -y jq
      - run: sudo apt-get install -y cppcheck
      - run: sudo apt-get install -y bc
      - run: sudo apt-get install -y ghc
      - run: sudo apt-get install -y sbcl
      - run: sudo apt-get install -y fpc
      - uses: actions/checkout@v4
      - run: make env
      - run: make sa
      - run: sudo make FAST=1 INPUT=7
